const products = [
  {
    id: 0,
    name: "Hoddies 1",
    price: 29.99,
    instock: 100,
    description: "Lorem ipsum dolor sit amet, consectetur.",
    imgSrc: "./img/product_01.jpg",
  },
  {
    id: 1,
    name: "Hoddies 2",
    price: 24.99,
    instock: 43,
    description: "Lorem ipsum dolor sit amet, consectetur.",
    imgSrc: "./img/product_02.jpg",
  },
  {
    id: 2,
    name: "Hoddies 3",
    price: 19.99,
    instock: 10,
    description: "Lorem ipsum dolor sit amet, consectetur.",
    imgSrc: "./img/product_03.jpg",
  },
  {
    id: 3,
    name: "Hoddies 4",
    price: 25.99,
    instock: 5,
    description: "Lorem ipsum dolor sit amet, consectetur.",
    imgSrc: "./img/product_04.jpg",
  },
  {
    id: 4,
    name: "Hoddies 5",
    price: 29.99,
    instock: 4,
    description: "Lorem ipsum dolor sit amet, consectetur.",
    imgSrc: "./img/product_06.jpg",
  },
  {
    id: 5,
    name: "Hoddies 6",
    price: 39.99,
    instock: 40,
    description: "Lorem ipsum dolor sit amet, consectetur.",
    imgSrc: "./img/product_07.jpg",
  },
  {
    id: 6,
    name: "Hoddies 7",
    price: 39.99,
    instock: 40,
    description: "Lorem ipsum dolor sit amet, consectetur.",
    imgSrc: "./img/product_08b.jpg",
  },
  {
    id: 7,
    name: "Hoddies 8",
    price: 39.99,
    instock: 40,
    description: "Lorem ipsum dolor sit amet, consectetur.",
    imgSrc: "./img/product_08.jpg",
  },
];
